# Generated by Django 6.0.5 on 2026-05-25 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('floor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('sheltered', models.BooleanField(default=False)),
                ('stairs', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=1.0)),
                ('unit', models.CharField(default='m', max_length=20)),
                ('duration', models.FloatField()),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_end', to='compass.node')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_start', to='compass.node')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('floor', models.IntegerField(default=0)),
                ('nodes', models.ManyToManyField(blank=True, to='compass.node')),
            ],
        ),
    ]
