# Generated by Django 6.0.5 on 2026-05-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='unit',
            field=models.CharField(choices=[('metres', 'metres'), ('steps', 'steps'), ('seconds', 'seconds')], default='metres', max_length=20),
        ),
    ]
