# Generated by Django 6.0.5 on 2026-05-27 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0002_alter_edge_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacencyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjacent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacent_node', to='compass.node')),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.edge')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacency_node', to='compass.node')),
            ],
        ),
    ]
