# Generated by Django 6.0.5 on 2026-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0003_adjacencylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
