# Generated by Django 6.0.5 on 2026-07-14 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.CharField(max_length=10)),
                ('day', models.CharField(choices=[('Weekday', 'Weekday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('waitAve', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=10, default=0.0, max_digits=17)),
                ('lng', models.DecimalField(decimal_places=10, default=0.0, max_digits=17)),
                ('floor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=10, default=0.0, max_digits=17)),
                ('lng', models.DecimalField(decimal_places=10, default=0.0, max_digits=17)),
                ('floor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('sheltered', models.BooleanField(default=False)),
                ('stairs', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=1.0)),
                ('unit', models.CharField(choices=[('metres', 'metres'), ('steps', 'steps'), ('seconds', 'seconds')], default='metres', max_length=20)),
                ('duration', models.FloatField(default=0.0)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_end', to='compass.node')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_start', to='compass.node')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=10, default=0.0, max_digits=17)),
                ('lng', models.DecimalField(decimal_places=10, default=0.0, max_digits=17)),
                ('floor', models.IntegerField(default=0)),
                ('nodes', models.ManyToManyField(blank=True, to='compass.node')),
            ],
        ),
        migrations.CreateModel(
            name='AdjacencyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.edge')),
                ('adjacent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacent_node', to='compass.node')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacency_node', to='compass.node')),
            ],
        ),
    ]
