# Generated by Django 6.0.5 on 2026-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='bus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
