# Generated by Django 6.0.5 on 2026-06-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.CharField(max_length=10)),
                ('day', models.CharField(choices=[('Weekday', 'Weekday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('waitAve', models.FloatField(default=0.0)),
            ],
        ),
    ]
