# Generated by Django 6.0.5 on 2026-07-25 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0002_edge_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('mean', models.FloatField(default=0.0)),
                ('M2', models.FloatField(default=0.0)),
                ('values', models.JSONField(default=list)),
                ('edge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate', to='compass.edge')),
            ],
        ),
    ]
